package interfaces.performance;

import interfaces.FrameMain;
import interfaces.informes.IFrameInforme1;
import interfaces.itinerarios.IFrameItinerarios;
import javax.swing.JDesktopPane;

/**
 *
 * @author USUARIO
 */
public class IFramePerformance extends javax.swing.JInternalFrame {

    
    
    private JDesktopPane panel;
    private FrameMain frame;
    
    public IFramePerformance(JDesktopPane panel, FrameMain frame) {
        initComponents();
        this.panel = panel;
        this.frame = frame;
        this.setLocation(panel.getWidth()/2-this.getWidth()/2,panel.getHeight()/2-this.getHeight()/2);
    }
    
    public IFramePerformance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Informes de Rendimiento");

        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        jButton1.setText("Itinerarios Realizados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Entrenamientos Realizados");
        jPanel1.add(jButton2);

        jButton3.setText("Gráfico entrenamiento Semanal");
        jPanel1.add(jButton3);

        jButton4.setText("Entrenamientos / Tipo de Entrenamiento");
        jPanel1.add(jButton4);

        jButton5.setText("Itinerarios / Grados de Dificultad");
        jPanel1.add(jButton5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frame.cerrarDialogosAbiertos();
        IFrameInforme1 iFrameInforme1 = new IFrameInforme1(panel, frame);
        panel.add(iFrameInforme1);
        iFrameInforme1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
