/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.itinerarios;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Alex
 */
public class JDImg extends javax.swing.JDialog {

    String file;

    /**
     * Creates new form JDImg
     */
    public JDImg(java.awt.Frame parent, boolean modal, String file) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.file = file;
        ImgGrande.setIcon(new ImageIcon(file));
        //Modificamos la imagen
        ImageIcon icon = new ImageIcon(file);
        //Extraemos la imagen del icono
        Image img = icon.getImage();
        //Cambiamos el tamaño de la imagen
        Image newimg = img.getScaledInstance(756, 449, java.awt.Image.SCALE_SMOOTH);
        //Se genera el ImageIcon con la nueva imagen
        ImageIcon newIcon = new ImageIcon(newimg);
        ImgGrande.setIcon(newIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgGrande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgGrande, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgGrande, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgGrande;
    // End of variables declaration//GEN-END:variables
}
